name: deploy netlify
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install angular-cli
        run: npm install @angular/cli@latest --force
      - name: list dir
        run: pwd
      - name: build
        run: npm run build
      - name: list dir
        run: cd dist && ls
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: list
        run: pwd && ls
      - name: deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
            publish-dir: './dist/schema-builder'
            production-branch: master
            deploy-message: "Deploy from GitHub Actions"
            enable-pull-request-comment: true
            enable-commit-comment: true
            overwrites-pull-request-comment: true
        env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
